version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.414.3
    container_name: jenkins-upgraded
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
    command: ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.21
    container_name: artifactory
    restart: unless-stopped
    ports:
      - "8081:8081"

  postgres:
    image: postgres:9.6.11
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  socat:
    image: alpine/socat
    container_name: socat
    restart: unless-stopped
    command: socat tcp-listen:2375,fork,reuseaddr tcp-connect:docker:2375
    ports:
      - "2375:2375"

volumes:
  jenkins_home:

